/*
 * Hyperfoil Controller API
 * Hyperfoil Controller API
 *
 * The version of the OpenAPI document: 0.5
 * Contact: rvansa@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.jboss.intersmash.tools.provision.openshift.operator.hyperfoil.client.v05.invoker.auth;

import java.net.URI;
import java.util.List;
import java.util.Map;

import org.jboss.intersmash.tools.provision.openshift.operator.hyperfoil.client.v05.invoker.ApiException;
import org.jboss.intersmash.tools.provision.openshift.operator.hyperfoil.client.v05.invoker.Pair;

public interface Authentication {
	/**
	 * Apply authentication settings to header and query params.
	 *
	 * @param queryParams List of query parameters
	 * @param headerParams Map of header parameters
	 * @param cookieParams Map of cookie parameters
	 * @param payload HTTP request body
	 * @param method HTTP method
	 * @param uri URI
	 * @throws ApiException if failed to update the parameters
	 */
	void applyToParams(List<Pair> queryParams, Map<String, String> headerParams, Map<String, String> cookieParams,
			String payload, String method, URI uri) throws ApiException;
}
