name: Intersmash - Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style-check:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Check source code formatting, file headers, etc.
        run: mvn -T 1C spotless:check --batch-mode -Daether.dependencyCollector.impl=bf
