name: Kubernetes E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-e2e-intersmash-${{ github.ref }}
  cancel-in-progress: true

jobs:
  minikube:
    name: "K8S Integration tests on K8S: ${{ matrix.kubernetes }} with JDK: ${{ matrix.java-version }}"
    runs-on: ubuntu-latest
    if: github.repository == 'Intersmash/intersmash'
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.35.2]
        java-version: ['17','21']
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.18.0
        with:
          driver: docker
          minikube version: 'v1.38.1'
          kubernetes version: ${{ matrix.kubernetes }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: "--memory='4gb' --cpus='2'"
      - name: Install operator-sdk
        run: |
          set -x
          #
          # operator-sdk must be installed manually on K8s
          #
          export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
          export OS=$(uname | awk '{print tolower($0)}')
          export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.41.1
          curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
          chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk
          operator-sdk olm install
      - name: Mirror hyperfoil kube-rbac-proxy image needed by Hyperfoil
        run: minikube ssh "docker pull registry.k8s.io/kubebuilder/kube-rbac-proxy:v0.15.0 && docker tag registry.k8s.io/kubebuilder/kube-rbac-proxy:v0.15.0 gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0"
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Prepare local Maven repository
        run: |
          set -x
          mkdir local-repo
          set +x
      - name: Pre-fetch dependencies
        run: mvn clean install -T 1C -pl kubernetes-client,core,provisioners,testsuite,testsuite/deployments,testsuite/deployments/deployments-provider -am --batch-mode -Dmaven.repo.local=./local-repo -DskipTests -Daether.dependencyCollector.impl=bf
      - name: Run Integration Tests
        run: |
          mvn test -e --batch-mode -fae -Dmaven.repo.local=./local-repo -pl testsuite/integration-tests -Pts.k8s \
          -Dintersmash.kubernetes.url=https://$(minikube ip):8443 \
          -Dintersmash.kubernetes.route_domain=$(minikube ip) \
          -Dintersmash.kubernetes.hostname=$(minikube ip) \
          -Dintersmash.kubernetes.namespace=test-k8s-1 \
          -Dintersmash.olm.operators.catalog_source=operatorhubio-catalog \
          -Dintersmash.olm.operators.namespace=olm \
          -Dintersmash.hyperfoil.operators.catalog_source=operatorhubio-catalog
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: logs-${{ matrix.kubernetes }}
          path: |
            **/log/*
            **/target/surefire-reports/*
